/*
Creates a table which has four columns
    - IF NOT EXISTS prevents the creation of the table if the table already exists
 */
CREATE TABLE IF NOT EXISTS whopipe_video_views(
    view_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    video_name TEXT NOT NULL,
    region TEXT NOT NULL,
    date_viewed TIMESTAMP DEFAULT now() NOT NULL
);

/*
Creates a new type called department as a ENUM (list of options that may be used by columns in a table)
    -IF NOT EXISTS does not work for TYPE so, DROP and then CREATE TYPE
*/
DROP TYPE IF EXISTS department;
CREATE TYPE department AS ENUM (
    'Electronics',
    'Cleaning',
    'Grocery',
    'Furniture',
    'Stationary',
    'Clothing',
    'DIY',
    'Sports',
    'Homeware',
    'Games',
    'Transport'
);

/*
Creates a table amazong_products
    - Price is set to a decimal which can be 12 in "precision" and 2 decimal points
    - Catergory has the type Department which we created, so this value would have to be any of the ones listed in that type
        - anything else will not be accepted
*/
CREATE TABLE IF NOT EXISTS amazong_products (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    image TEXT,
    category department NOT NULL
);