CREATE TABLE blogful_articles(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL,
    content TEXT
);
/*TIMESTAMPTZ type with means timestamp with time zone -- forces all time stamps to be recorded in UTC time*/